# handlers will be executer sequentially up to the point when some returns
# response so make sure that last one will return it

pipelines:
  main:
    methods:
      - post
      - get

    handlers:
      - handler: cip.handlers.soap.SoapHandler
        xsd: config/nomis.xsd
        soap_xsd: config/soap.xsd
        wsdl: config/wsdl.xml
        service_url: http://172.22.16.3:5000/main

      - handler: cip.handlers.request.RequestHandler
        url: http://172.22.16.2:9006/PrisonVisitBookingService/PrisonVisitBookingOperationsService

  direct:
    methods:
      - post

    handlers:
      - handler: cip.handlers.request.RequestHandler
        url: http://172.22.16.2:9006/PrisonVisitBookingService/PrisonVisitBookingOperationsService

  dummy:
    methods:
      - post

    handlers:
      - handler: cip.handlers.soap.SoapHandler
        xsd: config/nomis.xsd
        soap_xsd: config/soap.xsd

      - handler: cip.handlers.request.RequestHandler
        url: http://localhost:5000/dummy

routes:
  /ws:
    pipeline: direct
  /main:
    pipeline: main
  /dummy:
    pipeline: dummy

hide_errors: false
log_file: cip.log

#flask options
DEBUG: True

collectd_host: 127.0.0.1
collectd_port: 8125