# handlers will be executer sequentially up to the point when some returns
# response so make sure that last one will return it

pipelines:
  main:
    methods:
      - post
      - get

    handlers:
      - handler: cip.handlers.throttling.ThrottlingHandler
        limit: 30

      - handler: cip.handlers.soap.SoapHandler
        xsd: config/nomis.xsd
        soap_xsd: config/soap.xsd
        wsdl: config/wsdl.xml
        service_url: http://nomis.local/PrisonVisitBookingService/PrisonVisitBookingOperationsService

      - handler: cip.handlers.request.RequestHandler
        verify: True
        url: http://nomis.local/PrisonVisitBookingService/PrisonVisitBookingOperationsService

  direct:
    methods:
      - post

    handlers:
      - handler: cip.handlers.throttling.ThrottlingHandler
        limit: 30

      - handler: cip.handlers.request.RequestHandler
        url: http://nomis.local/PrisonVisitBookingService/PrisonVisitBookingOperationsService

  dummy:
    methods:
      - get
      - post

    handlers:
      - handler: cip.handlers.soap.SoapHandler
        xsd: config/nomis.xsd
        soap_xsd: config/soap.xsd

      - handler: cip.handlers.utils.ReturningHandler
        code: 200
        data: '<success>Bingo</success>'

  health:
    methods:
      - get

    handlers:
      - handler: cip.handlers.throttling.ThrottlingHandler
        limit: 1

      - handler: cip.handlers.utils.ReturningHandler
        code: 200
        data: OK


routes:
  /PrisonVisitBookingService/PrisonVisitBookingOperationsService:
    pipeline: main
  /dummy:
    pipeline: dummy
  /health:
    pipeline: health

#log_file: /cip/cip/cip.log

#flask options
DEBUG: False

statsd:
  enabled: True
  host: 127.0.0.1
  port: 8125
  prefix: 'cip'

logstash:
  enabled: True
  host: 127.0.0.1
  port: 5959
  version: 1
