# handlers will be executer sequentially up to the point when some returns
# response so make sure that last one will return it

pipelines:
  main:
    handlers:
      - handler: cip.handlers.throttling.ThrottlingHandler
        limit: 10
        per: 1
        burst: 5

      - handler: cip.handlers.soap.SoapHandler
        xsd: config/nomis.xml

      - handler: cip.handlers.request.RequestHandler
        url: http://127.0.0.1:12345/api

  simple:
    handlers:
      - handler: cip.handlers.request.RequestHandler
        url: http://127.0.0.1:12345/api

  test:
    methods:
      - get
      - post

    handlers:
      - handler: cip.handlers.request.RequestHandler
        url: http://google.com/


routes:
  /ws:
    pipeline: test
  /main:
    pipeline: main

environment: staging

xml_config:
  custom_def: config/moj.xsd
  transformations:
     xs:string: moj:LimitedString


#flask options
DEBUG: True
