# handlers will be executer sequentially up to the point when some returns
# response so make sure that last one will return it

pipelines:
  main:
    methods:
      - post
      - get

    handlers:
      - handler: cip.handlers.soap.SoapHandler
        xsd: config/nomis.xsd
        soap_xsd: config/soap.xsd
        wsdl: http://nomis.local/PrisonVisitBookingService/PrisonVisitBookingOperationsService?wsdl
        service_url: http://nomis.local/PrisonVisitBookingService/PrisonVisitBookingOperationsService

      - handler: cip.handlers.request.RequestHandler
        url: http://nomis.local/PrisonVisitBookingService/PrisonVisitBookingOperationsService

  direct:
    methods:
      - post

    handlers:
      - handler: cip.handlers.request.RequestHandler
        url: http://nomis.local/PrisonVisitBookingService/PrisonVisitBookingOperationsService

  dummy:
    methods:
      - post

    handlers:
      - handler: cip.handlers.soap.SoapHandler
        xsd: config/nomis.xsd
        soap_xsd: config/soap.xsd

      - handler: cip.handlers.request.RequestHandler
        url: http://localhost:5000/dummy

routes:
  /ws:
    pipeline: direct
  /PrisonVisitBookingService/PrisonVisitBookingOperationsService:
    pipeline: main
  /dummy:
    pipeline: dummy

hide_errors: false
#log_file: /cip/cip/cip.log

#flask options
DEBUG: True

collectd_host: 127.0.0.1
collectd_port: 8125
