all:
	wget http://172.22.16.2:9006/PrisonVisitBookingService/PrisonVisitBookingOperationsService?wsdl -O wsdl.xml
	wget http://172.22.16.2:9006/PrisonVisitBookingService/PrisonVisitBookingOperationsService?xsd=1 -O xsd.xml
