all:
	curl http://172.22.16.2:9006/PrisonVisitBookingService/PrisonVisitBookingOperationsService?wsdl -o wsdl.xml
	curl http://172.22.16.2:9006/PrisonVisitBookingService/PrisonVisitBookingOperationsService?xsd=1 -o xsd.xml
