base_url: http://127.0.0.1:5000

fixtures:
  - name: check prisoner info
    method: post
    url: /PrisonVisitBookingService/PrisonVisitBookingOperationsService
    headers:
      Content-Type: text/xml
    data: check_prisoner_info
    success: 200

  - name: get available timeslots with invalid data
    method: post
    url: /PrisonVisitBookingService/PrisonVisitBookingOperationsService
    headers:
      Content-Type: text/xml
    data: get_available_timeslots
    success: 500

  - name: test wsdl
    method: get
    url: /PrisonVisitBookingService/PrisonVisitBookingOperationsService?wsdl
    success: 200

  - name: test xsd
    method: get
    url: /PrisonVisitBookingService/PrisonVisitBookingOperationsService?xsd=1
    success: 200
