# handlers will be executed sequentially up to the point when some returns response
# so make sure that last one will return it

pipelines:
  main:
    handlers:
      - handler: cip.handlers.throttling.ThrottlingHandler
        limit: 10
        per: 1

      - handler: cip.handlers.soap.SoapHandlerMock
        wsdl: config/wsdl.xml
        xsd: config/nomis.xsd
        soap_xsd: config/soap.xsd
        xml_config:
          custom_def: config/moj.xsd
          transformations:
             xs:string: moj:LimitedString

      - handler: cip.handlers.request.RequestHandlerMock
        url: http://127.0.0.1/api

  test:
    handlers:
      - handler: cip.handlers.request.RequestHandlerMock
        url: http://127.0.0.1:4000/ws

  test_slash:
    handlers:
      - handler: cip.handlers.request.RequestHandlerMock
        url: http://127.0.0.1:4000/ws/

  test_mock:
    methods:
      - get
      - post

    handlers:
      - handler: cip.handlers.request.RequestHandlerMock
        url: http://127.0.0.1:4000/ws

  test_soap:
    methods:
      - post

    handlers:
      - handler: cip.handlers.soap.SoapHandlerMock
        xsd: config/nomis.xsd
        soap_xsd: config/soap.xsd
        request_size: 4096

  test_small_soap:
    methods:
      - post

    handlers:
      - handler: cip.handlers.soap.SoapHandlerMock
        request_size: 5
        xsd: config/nomis.xsd
        soap_xsd: config/soap.xsd


  test_enhanced_soap:
    methods:
      - post

    handlers:
      - handler: cip.handlers.soap.SoapHandlerMock
        xsd: config/nomis.xsd
        soap_xsd: config/soap.xsd

      - handler: cip.handlers.request.RequestHandlerMock
        url: http://google.com/ws

  test_throttling:
    methods:
      - get
    handlers:
      - handler: cip.handlers.throttling.ThrottlingHandler
        limit: 1
        per: 1

      - handler: cip.handlers.utils.ReturningHandler
        code: 200
        data: OK

  test_latency:
    methods:
      - get
    handlers:
      - handler: cip.handlers.latency.LatencyHandler
        delay_request: 0.3
        delay_response: 0.3

      - handler: cip.handlers.utils.ReturningHandler
        code: 200
        data: OK

routes:
  /test:
    pipeline: test

  /slash/:
    pipeline: test_slash

  /mock:
    pipeline: test_mock

  /soap:
    pipeline: test_soap

  /more_soap:
    pipeline: test_enhanced_soap

  /little_soap:
    pipeline: test_small_soap

  /throttling:
    pipeline: test_throttling

  /latency:
    pipeline: test_latency

#flask options
DEBUG: False

#log_file: ../cip.log

collectd:
  enabled: True
  host: 127.0.0.1
  port: 8125

logstash:
  enabled: False
  host: 127.0.0.1
  port: 5959
  version: 1
