# handlers will be executed sequentially up to the point when some returns response
# so make sure that last one will return it

pipelines:
  main:
    handlers:
      - handler: cip.handlers.throttling.ThrottlingHandler
        limit: 10
        per: 1

      - handler: cip.handlers.soap.SoapHandlerMock
        wsdl: config/wsdl.xml
        xsd: config/nomis.xsd
        soap_xsd: config/soap.xsd
        xml_config:
          custom_def: config/moj.xsd
          transformations:
             xs:string: moj:LimitedString

      - handler: cip.handlers.request.RequestHandlerMock
        url: http://127.0.0.1/api

  test:
    handlers:
      - handler: cip.handlers.request.RequestHandlerMock
        url: http://127.0.0.1:4000/ws

  test_slash:
    handlers:
      - handler: cip.handlers.request.RequestHandlerMock
        url: http://127.0.0.1:4000/ws/

  test_mock:
    methods:
      - get
      - post

    handlers:
      - handler: cip.handlers.request.RequestHandlerMock
        url: http://127.0.0.1:4000/ws

  test_soap:
    methods:
      - post

    handlers:
      - handler: cip.handlers.soap.SoapHandlerMock
        xsd: config/nomis.xsd
        soap_xsd: config/soap.xsd
        request_size: 4096

  test_small_soap:
    methods:
      - post

    handlers:
      - handler: cip.handlers.soap.SoapHandlerMock
        request_size: 5
        xsd: config/nomis.xsd
        soap_xsd: config/soap.xsd


  test_enhanced_soap:
    methods:
      - post

    handlers:
      - handler: cip.handlers.soap.SoapHandlerMock
        xsd: config/nomis.xsd
        soap_xsd: config/soap.xsd

      - handler: cip.handlers.request.RequestHandlerMock
        url: http://google.com/ws

routes:
  /test:
    pipeline: test

  /slash/:
    pipeline: test_slash

  /mock:
    pipeline: test_mock

  /soap:
    pipeline: test_soap

  /more_soap:
    pipeline: test_enhanced_soap

  /little_soap:
    pipeline: test_small_soap

hide_errors: false
#flask options
DEBUG: True

#log_file: ../cip.log

collectd_host: 172.16.195.135
collectd_port: 8125